"""Initial migration

Revision ID: 90190a9ad4f9
Revises: 
Create Date: 2025-08-10 16:55:04.971686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90190a9ad4f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_type', sa.Enum('STAFF', 'CUSTOMER', name='author_type'), nullable=False),
    sa.Column('category', sa.Enum('UX', 'PRODUCT', 'SERVICE', 'OPERATIONAL', 'OTHER', name='category'), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PROCESSED', 'ARCHIVED', name='suggestion_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('engine', sa.Enum('MD_JINJA', name='template_engine'), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('outline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('placeholders', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('EMBEDDING', 'TAG', 'TOPIC', 'FUSION', name='cluster_kind'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_REVIEW', 'IN_PROGRESS', 'CLOSED', 'ARCHIVED', name='cluster_status'), nullable=True),
    sa.Column('primary_topic_id', sa.UUID(), nullable=True),
    sa.Column('fusion_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RENDERING', 'READY', 'FAILED', name='doc_status'), nullable=False),
    sa.Column('rendered_format', sa.Enum('PDF', 'DOCX', name='doc_format'), nullable=True),
    sa.Column('rendered_url', sa.Text(), nullable=True),
    sa.Column('draft_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestion_tags',
    sa.Column('suggestion_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('suggestion_id', 'tag_id')
    )
    op.create_table('topic_aliases',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'alias')
    )
    op.create_table('cluster_members',
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('suggestion_id', sa.UUID(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], ),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_table('document_clusters',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('contribution_weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'cluster_id')
    )
    op.create_table('document_tags',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'tag_id')
    )
    op.create_table('document_topics',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'topic_id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_table('document_topics')
    op.drop_table('document_tags')
    op.drop_table('document_clusters')
    op.drop_table('cluster_members')
    op.drop_table('topic_aliases')
    op.drop_table('suggestion_tags')
    op.drop_table('documents')
    op.drop_table('clusters')
    op.drop_table('topics')
    op.drop_table('templates')
    op.drop_table('tags')
    op.drop_table('suggestions')
    op.drop_table('jobs')
    # ### end Alembic commands ###